stages:
  - test

testing:
  image: python:3.6
  stage: test
  variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/pip-cache"
  before_script:
    - pip3 install -r requirements.txt
  script:
    - nosetests
