stages:
  - test
  - package

testing:
  image: python:3.6
  stage: test
  variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/pip-cache"
  before_script:
    - pip3 install -r requirements.txt
  script:
    - nosetests

building:
  image: python:3.6
  stage: test
  variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/pip-cache"
  before_script:
    - pip3 install -r requirements.txt
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}"
    expire_in: '6 months'
    paths:
      - dist/*

publish:
  image: python:3.6
  stage: build
  variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/pip-cache"
  before_script:
    - pip install twine
  script:
    - >
      twine upload --repository-url https://test.pypi.org/legacy/ dist/*
      --username ${PYPI_USERNAME} --password ${PYPI_PASSWORD}
